#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

dest_dir=${OPENSHIFT_DATA_DIR}html

if [ ! -d "${dest_dir}" ]; then
  mkdir -p $dest_dir
fi

ln -sf ${OPENSHIFT_DATA_DIR}html ${OPENSHIFT_REPO_DIR}public
